In [ ]:
import numpy as np
import matplotlib.pyplot as plt

#**Funções**

## *Matriz triangular superior*

In [ ]:
def gpt_calcula_solucao_matriz_triangular_superior(A, B):
    n = len(A)
    X = np.zeros((n, 1), dtype=float)

    for i in range(n - 1, -1, -1):
        X[i] = (B[i] - np.dot(A[i, i+1:], X[i+1:])) / A[i, i]

    return X

## *Matriz triangular superior*

In [ ]:
def gpt_calcula_solucao_matriz_triangular_superior(A, B):
    n = len(A)
    X = np.zeros((n, 1), dtype=float)

    for i in range(n - 1, -1, -1):
        X[i] = (B[i] - np.dot(A[i, i+1:], X[i+1:])) / A[i, i]

    return X

## *Eliminação Gaussiana*

In [ ]:
def eliminacao_gauss(A, B):
    A_copia = np.copy(A)
    B_copia = np.copy(B)

    for i in range(len(A_copia) - 1):
        pivo = A_copia[i, i]

        for j in range(i + 1, len(A_copia)):
            m = -A_copia[j, i] / pivo
            A_copia[j, :] += A_copia[i, :] * m
            B_copia[j] += B_copia[i] * m

    return A_copia, B_copia

## *Pivoteamento parcial*





In [ ]:
def eliminacao_gauss_pivot(A, B):
    A_copia = np.copy(A)
    B_copia = np.copy(B)

    for i in range(len(A_copia) - 1):
        pivo = A_copia[i, i]

        z = i+1
        find = False
        line = i

######################################################## inicio troca das linhas
        while z < len(A_copia):
            if abs(A_copia[z, i]) > abs(pivo):
                pivo = A_copia[z, i]
                line = z
                find = True
            z += 1

        if find:
            Aux = np.copy(A_copia)
            A_copia[i,:] = np.copy(A_copia[line,:])
            A_copia[line,:] = np.copy(Aux[i,:])
            Aux = np.copy(B_copia)
            B_copia[i] = B_copia[line]
            B_copia[line] = Aux[i]
######################################################### final troca das linhas

        for j in range(i + 1, len(A_copia)):
            m = -A_copia[j, i] / pivo
            A_copia[j, :] += A_copia[i, :] * m
            B_copia[j] += B_copia[i] * m

    return A_copia, B_copia

In [ ]:
def gpt_eliminacao_gauss_pivot(A, B):
    A_copia = np.copy(A)
    B_copia = np.copy(B)
    n = len(A_copia)

    for i in range(n - 1):
        pivot_row = i
        max_pivot = abs(A_copia[i, i])

        # Find the row with the maximum pivot element
        for j in range(i + 1, n):
            current_pivot = abs(A_copia[j, i])
            if current_pivot > max_pivot:
                pivot_row = j
                max_pivot = current_pivot

        # Swap rows if needed
        if pivot_row != i:
            A_copia[[i, pivot_row]] = A_copia[[pivot_row, i]]
            B_copia[i], B_copia[pivot_row] = B_copia[pivot_row], B_copia[i]

        for j in range(i + 1, n):
            m = -A_copia[j, i] / A_copia[i, i]
            A_copia[j, :] += A_copia[i, :] * m
            B_copia[j] += B_copia[i] * m

    return A_copia, B_copia


## *Checagem do pivo*


In [ ]:
def check_null_pivot(A, B):
    A_copia = np.copy(A)
    B_copia = np.copy(B)

    for i in range(len(A_copia) - 1):
        pivo = A_copia[i, i]

        if pivo == 0:
            z = i+1
            find = False
            line = i

            while z < len(A_copia):
                if abs(A_copia[z, i]) > abs(pivo):
                    pivo = A_copia[z, i]
                    line = z
                    find = True
                z += 1

            if find:
                Aux = np.copy(A_copia)
                A_copia[i,:] = np.copy(A_copia[line,:])
                A_copia[line,:] = np.copy(Aux[i,:])
                Aux = np.copy(B_copia)
                B_copia[i] = B_copia[line]
                B_copia[line] = Aux[i]

    return A_copia, B_copia

## *Eliminacao Gauss Jordan*




In [ ]:
def eliminacao_gauss_jordan(A, B):
    A_copia = np.copy(A)
    B_copia = np.copy(B)

    for i in range(len(A_copia)):
        pivo = A_copia[i, i]
        A_copia[i,:] /= pivo
        B_copia[i] /= pivo

        for j in range(0, len(A_copia)):
            if j != i:
                m = -A_copia[j, i]
                A_copia[j, :] += A_copia[i, :] * m
                B_copia[j] += B_copia[i] * m

    return A_copia, B_copia

## *Inversa via Gauss Jordan*

In [ ]:
def inversa_gauss_jordan(A):
    A_copia = np.copy(A)
    B_copia = np.eye(len(A))

    for i in range(len(A_copia)):
        pivo = A_copia[i, i]
        A_copia[i,:] /= pivo
        B_copia[i] /= pivo

        for j in range(0, len(A_copia)):
            if j != i:
                m = -A_copia[j, i]
                A_copia[j, :] += A_copia[i, :] * m
                B_copia[j, :] += B_copia[i, :] * m

    return B_copia

## Decomposição LU

In [ ]:
def LU_decomposition(A):
    n = A.shape[0]
    U, L = A.copy(), np.eye(n)

    for i in range(n):
        for j in range(i+1, n):
            coef = -U[j, i] / U[i, i]
            L[j, i] = coef
            U[j] += U[i] * coef

    return L, U

#**1 - Calcule a inversa da matriz 𝑨 usando eliminação gaussiana com pivoteamento parcial.**

In [ ]:
ordem = 3

A = np.zeros([ordem, ordem], dtype='float')

A =[[1.0, 2.0, -1.0],
    [-1.0, 2.0, 0.0],
    [2.0, 1.0, -1.0]]

A = np.array(A)

A

array([[ 1.,  2., -1.],
       [-1.,  2.,  0.],
       [ 2.,  1., -1.]])

In [ ]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
B1 = I[:, 0]
B2 = I[:, 1]
B3 = I[:, 2]

print(B1, B2, B3)

[1. 0. 0.] [0. 1. 0.] [0. 0. 1.]


In [ ]:
[Ac1, Bc1] = eliminacao_gauss_pivot(A, B1)
x1 = gpt_calcula_solucao_matriz_triangular_superior(Ac1, Bc1)

[Ac2, Bc2] = eliminacao_gauss_pivot(A, B2)
x2 = gpt_calcula_solucao_matriz_triangular_superior(Ac2, Bc2)

[Ac3, Bc3] = eliminacao_gauss_pivot(A, B3)
x3 = gpt_calcula_solucao_matriz_triangular_superior(Ac3, Bc3)

sol = np.zeros([ordem, ordem], dtype='float')
sol = np.column_stack((x1, x2, x3))
sol

array([[-2.,  1.,  2.],
       [-1.,  1.,  1.],
       [-5.,  3.,  4.]])

In [ ]:
res = A@sol
print(res)

[[1.0000000e+00 4.4408921e-16 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]


In [ ]:
[Ac1, Bc1] = gpt_eliminacao_gauss_pivot(A, B1)
x1 = gpt_calcula_solucao_matriz_triangular_superior(Ac1, Bc1)

[Ac2, Bc2] = gpt_eliminacao_gauss_pivot(A, B2)
x2 = gpt_calcula_solucao_matriz_triangular_superior(Ac2, Bc2)

[Ac3, Bc3] = gpt_eliminacao_gauss_pivot(A, B3)
x3 = gpt_calcula_solucao_matriz_triangular_superior(Ac3, Bc3)

sol = np.zeros([ordem, 1], dtype='float')
sol = np.column_stack((x1, x2, x3))
sol

array([[-2.,  1.,  2.],
       [-1.,  1.,  1.],
       [-5.,  3.,  4.]])

In [ ]:
res = A@sol
print(res)

[[1.0000000e+00 4.4408921e-16 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]


#**2 - Resolva o seguinte sistema de equações lineares usando eliminação gaussiana com pivoteamento parcial:**

In [ ]:
ordem = 3

A = np.zeros([ordem, ordem], dtype='float')
B = np.zeros([ordem, 1], dtype='float')

A =[[1.0, 1.0, 1.0],
    [1.0, 0.0, 10.0],
    [0.0, 10.0, 1.0]]

B = [[0.0],
     [-48.0],
     [25.0]]

A = np.array(A)
B = np.array(B)

In [ ]:
[Ac, Bc] = eliminacao_gauss_pivot(A, B)
x = gpt_calcula_solucao_matriz_triangular_superior(Ac, Bc)


sol = np.zeros([ordem, 1], dtype='float')
sol = np.column_stack((x))
sol

array([[ 2.,  3., -5.]])

#**3 - Resolva o seguinte sistema usando eliminação gaussiana sem e com pivoteamento parcial. Discuta, em cada caso, o resultado frente à aritmética de ponto flutuante quando 𝟎 < |𝜺| ≪ 𝟏:**

In [ ]:
ordem = 2

A = np.zeros([ordem, ordem], dtype='float')
B = np.zeros([ordem, 1], dtype='float')

A =[[1e-9, 2.0],
    [1.0, 1e-9]]

B = [[4.0],
     [3.0]]

A = np.array(A)
B = np.array(B)

In [ ]:
[Ac, Bc] = eliminacao_gauss(A, B)
x = gpt_calcula_solucao_matriz_triangular_superior(Ac, Bc)


sol = np.zeros([ordem, 1], dtype='float')
sol = np.column_stack((x))
sol

array([[2.9999998, 2.       ]])

In [ ]:
[Ac, Bc] = eliminacao_gauss_pivot(A, B)
x = gpt_calcula_solucao_matriz_triangular_superior(Ac, Bc)


sol = np.zeros([ordem, 1], dtype='float')
sol = np.column_stack((x))
sol

array([[3., 2.]])

#**4 - Use a fatoração LU para resolver o seguinte sistema linear:----------------------------------------------------------------------------------------------------------------------------------**

#**5 – Use eliminação de Gauss-Jordan para resolver:**

In [ ]:
ordem = 3

A = np.zeros([ordem, ordem], dtype='float')
B = np.zeros([ordem, 1], dtype='float')

A =[[2.0, 1.0, -1.0],
    [5.0, 2.0, 3.0],
    [3.0, 1.0, 1.0]]

B = [[1.0],
     [-4.0],
     [5.0]]

A = np.array(A)
B = np.array(B)

In [ ]:
[Ac, Bc] = check_null_pivot(A, B)
print(Ac)
print(Bc)


[[ 2.  1. -1.]
 [ 5.  2.  3.]
 [ 3.  1.  1.]]
[[ 1.]
 [-4.]
 [ 5.]]


In [ ]:
[Aj, Bj] = eliminacao_gauss_jordan(A, B)
print(Aj)
print(Bj)


sol = np.zeros([ordem, 1], dtype='float')
sol = np.column_stack((x))
sol

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[[ 10.66666667]
 [-23.66666667]
 [ -3.33333333]]


array([[ 10.66666667, -23.66666667,  -3.33333333]])

In [ ]:
res = A@Bj-B
print(res)

[[-2.22044605e-15]
 [-3.55271368e-15]
 [-1.77635684e-15]]


In [ ]:
Ainv = inversa_gauss_jordan(Ac)
print(Ac)
print(Ainv)

[[ 2.  1. -1.]
 [ 5.  2.  3.]
 [ 3.  1.  1.]]
[[-0.33333333 -0.66666667  1.66666667]
 [ 1.33333333  1.66666667 -3.66666667]
 [-0.33333333  0.33333333 -0.33333333]]


#**6 – Suponha que um time de três paraquedistas está ligado por uma corda sem peso enquanto cai, em queda livre, a uma velocidade de 5 m/s. Calcule a tensão em cada seção da corda e a aceleração do time, dado o seguinte:**