In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
ordem = int(input('Ordem do sistsema de eqs: '))
A = np.zeros([ordem, ordem], dtype='float')
B = np.zeros([ordem, 1], dtype='float')

Ordem do stsema de eqs: 4


In [6]:
for i in range(0, ordem):
    for j in range(0, ordem):
        A[i,j] = float(input('A[%d, %d] = ' %(i+1, j+1)))

for i in range(0, ordem):
    B[i] = float(input('B[%d] = ' %(i+1)))

print('\n', A, B)

A[1, 1] = 2
A[1, 2] = 0
A[1, 3] = 0
A[1, 4] = 0
A[2, 1] = 3
A[2, 2] = 5
A[2, 3] = 0
A[2, 4] = 0
A[3, 1] = 1
A[3, 2] = -6
A[3, 3] = 8
A[3, 4] = 0
A[4, 1] = -1
A[4, 2] = 4
A[4, 3] = -3
A[4, 4] = 9
B[1] = 4
B[2] = 1
B[3] = 48
B[4] = 6
[[ 2.  0.  0.  0.]
 [ 3.  5.  0.  0.]
 [ 1. -6.  8.  0.]
 [-1.  4. -3.  9.]] [[ 4.]
 [ 1.]
 [48.]
 [ 6.]]


In [12]:
def calcula_solucao_matriz_triangular_inferior(A, B):
    X = np.zeros([len(A), 1], dtype='float')
    i = 0

    while i < len(A):
        z= 0
        soma = 0

        while z < i:
            soma += A[i, z] * X[z]
            z += 1

        X[i] = (B[i] - soma) /  A[i,i]
        i += 1

    return X

In [15]:
def gpt_calcula_solucao_matriz_triangular_inferior(A, B):
    n = len(A)
    X = np.zeros((n, 1), dtype=float)

    for i in range(n):
        X[i] = (B[i] - np.dot(A[i, :i], X[:i])) / A[i, i]

    return X

In [13]:
calcula_solucao_matriz_triangular_inferior(A, B)

array([[ 2.],
       [-1.],
       [ 5.],
       [ 3.]])

In [16]:
gpt_calcula_solucao_matriz_triangular_inferior(A, B)

array([[ 2.],
       [-1.],
       [ 5.],
       [ 3.]])

In [21]:
ordem = int(input('Ordem do sistsema de eqs: '))
A = np.zeros([ordem, ordem], dtype='float')
B = np.zeros([ordem, 1], dtype='float')

Ordem do sistsema de eqs: 4


In [38]:
# for i in range(0, ordem):
#     for j in range(0, ordem):
#         A[i,j] = float(input('A[%d, %d] = ' %(i+1, j+1)))

A =[[5.0, -2.0, 6.0, 1.0],
    [0.0, 3.0, 7.0, -4.0],
    [0.0, 0.0, 4.0, 5.0],
    [0.0, 0.0, 0.0, 2.0]]

A = np.array(A)

# for i in range(0, ordem):
#     B[i] = float(input('B[%d] = ' %(i+1)))

B =[[ 1.],
    [-2.],
    [28.],
    [ 8.]]

B = np.array(B)


print('\n', A, B)


 [[ 5. -2.  6.  1.]
 [ 0.  3.  7. -4.]
 [ 0.  0.  4.  5.]
 [ 0.  0.  0.  2.]] [[ 1.]
 [-2.]
 [28.]
 [ 8.]]


In [39]:
def calcula_solucao_matriz_triangular_superior(A, B):
    X = np.zeros([len(A), 1], dtype='float')
    i = len(A) - 1

    while i >= 0:
        z= i + 1
        soma = 0

        while z < len(A):
            soma += A[i, z] * X[z]
            z += 1

        X[i] = (B[i] - soma) /  A[i,i]
        i -= 1

    return X

In [40]:
def gpt_calcula_solucao_matriz_triangular_superior(A, B):
    n = len(A)
    X = np.zeros((n, 1), dtype=float)

    for i in range(n - 1, -1, -1):
        X[i] = (B[i] - np.dot(A[i, i+1:], X[i+1:])) / A[i, i]

    return X

In [41]:
calcula_solucao_matriz_triangular_superior(A, B)

array([[-3.],
       [ 0.],
       [ 2.],
       [ 4.]])

In [42]:
gpt_calcula_solucao_matriz_triangular_superior(A, B)

array([[-3.],
       [ 0.],
       [ 2.],
       [ 4.]])

In [58]:
def eliminacao_gauss(A, B):
    A_copia = np.copy(A)
    B_copia = np.copy(B)

    for i in range(len(A_copia) - 1):
        pivo = A_copia[i, i]

        for j in range(i + 1, len(A_copia)):
            m = -A_copia[j, i] / pivo  # Corrected multiplier calculation
            A_copia[j, :] += A_copia[i, :] * m
            B_copia[j] += B_copia[i] * m

    return A_copia, B_copia

In [66]:
A =np.array([[ 1., -3., 2.],
             [-2., 8., -1.],
             [ 4., -6., 5.]])

print(A)

B =np.array([[ 11.],
             [-15.],
             [29.]])

print(B)

[[ 1. -3.  2.]
 [-2.  8. -1.]
 [ 4. -6.  5.]]
[[ 11.]
 [-15.]
 [ 29.]]


In [60]:
[A_tri_sup, B_tri_sup] = eliminacao_gauss(A, B)
print(A_tri_sup)
print(B_tri_sup)

[[  1.  -3.   2.]
 [  0.   2.   3.]
 [  0.   0. -12.]]
[[ 11.]
 [  7.]
 [-36.]]


In [61]:
xr = calcula_solucao_matriz_triangular_superior(A_tri_sup, B_tri_sup)
print(xr)

[[ 2.]
 [-1.]
 [ 3.]]


In [62]:
#cálculo do resíduo:
r = B - A@xr
print(r)

[[0.]
 [0.]
 [0.]]


In [71]:
def calcula_Det(A):
    A_copia = np.copy(A)
    n = len(A_copia)
    det = 1

    for i in range(n - 1):
        pivo = A_copia[i, i]

        for j in range(i + 1, n):
            m = -A_copia[j, i] / pivo  # Corrected multiplier calculation
            A_copia[j, :] += A_copia[i, :] * m

    for i in range(n):
        det *= A_copia[i, i]

    return det

In [72]:
A =np.array([[ 1., -3., 2.],
             [-2., 8., -1.],
             [ 4., -6., 5.]])

print(calcula_Det(A))

-24.0
