In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
ordem = int(input('Fornecer a ordem do sistema de equações: '))
A = np.zeros([ordem,ordem],dtype='float')
B = np.zeros([ordem,1],dtype='float')

Fornecer a ordem do sistema de equações: 4


In [3]:
for i in range(0,ordem):
    for j in range(0,ordem):
        A[i,j] = float(input('Elemento de pos. (%d,%d) da matriz A: ' %(i+1,j+1)))
        

for i in range(0,ordem):
    B[i] = float(input('Elemento de pos. %d do vetor B: ' %(i+1)))
    
print(A,B)
        

Elemento de pos. (1,1) da matriz A: 2
Elemento de pos. (1,2) da matriz A: 0
Elemento de pos. (1,3) da matriz A: 0
Elemento de pos. (1,4) da matriz A: 0
Elemento de pos. (2,1) da matriz A: 3
Elemento de pos. (2,2) da matriz A: 5
Elemento de pos. (2,3) da matriz A: 0
Elemento de pos. (2,4) da matriz A: 0
Elemento de pos. (3,1) da matriz A: 1
Elemento de pos. (3,2) da matriz A: -6
Elemento de pos. (3,3) da matriz A: 8
Elemento de pos. (3,4) da matriz A: 0
Elemento de pos. (4,1) da matriz A: -1
Elemento de pos. (4,2) da matriz A: 4
Elemento de pos. (4,3) da matriz A: -3
Elemento de pos. (4,4) da matriz A: 9
Elemento de pos. 1 do vetor B: 4
Elemento de pos. 2 do vetor B: 1
Elemento de pos. 3 do vetor B: 48
Elemento de pos. 4 do vetor B: 6
[[ 2.  0.  0.  0.]
 [ 3.  5.  0.  0.]
 [ 1. -6.  8.  0.]
 [-1.  4. -3.  9.]] [[ 4.]
 [ 1.]
 [48.]
 [ 6.]]


In [4]:
len(A)

4

In [5]:
def calcula_sol_mti(A,B):
    xr = np.zeros([len(A),1],dtype='float')
    idr = 0
    while idr < len(A):
        z = 0
        soma = 0
        while z < idr:
            soma = soma+A[idr,z]*xr[z]
            z=z+1
            
        xr[idr] = (B[idr]-soma)/A[idr,idr]
        idr=idr+1
        
    return(xr)
            
    

In [6]:
xr = calcula_sol_mti(A,B)
print(xr)

[[ 2.]
 [-1.]
 [ 5.]
 [ 3.]]


In [7]:
ordem = int(input('Fornecer a ordem do sistema de equações: '))
A = np.zeros([ordem,ordem],dtype='float')
B = np.zeros([ordem,1],dtype='float')

Fornecer a ordem do sistema de equações: 4


In [8]:
for i in range(0,ordem):
    for j in range(0,ordem):
        A[i,j] = float(input('Elemento de pos. (%d,%d) da matriz A: ' %(i+1,j+1)))
        

for i in range(0,ordem):
    B[i] = float(input('Elemento de pos. %d do vetor B: ' %(i+1)))
    
print(A,B)

Elemento de pos. (1,1) da matriz A: 5
Elemento de pos. (1,2) da matriz A: -2
Elemento de pos. (1,3) da matriz A: 6
Elemento de pos. (1,4) da matriz A: 1
Elemento de pos. (2,1) da matriz A: 0
Elemento de pos. (2,2) da matriz A: 3
Elemento de pos. (2,3) da matriz A: 7
Elemento de pos. (2,4) da matriz A: -4
Elemento de pos. (3,1) da matriz A: 0
Elemento de pos. (3,2) da matriz A: 0
Elemento de pos. (3,3) da matriz A: 4
Elemento de pos. (3,4) da matriz A: 5
Elemento de pos. (4,1) da matriz A: 0
Elemento de pos. (4,2) da matriz A: 0
Elemento de pos. (4,3) da matriz A: 0
Elemento de pos. (4,4) da matriz A: 2
Elemento de pos. 1 do vetor B: 1
Elemento de pos. 2 do vetor B: -2
Elemento de pos. 3 do vetor B: 28
Elemento de pos. 4 do vetor B: 8
[[ 5. -2.  6.  1.]
 [ 0.  3.  7. -4.]
 [ 0.  0.  4.  5.]
 [ 0.  0.  0.  2.]] [[ 1.]
 [-2.]
 [28.]
 [ 8.]]


In [9]:
def calcula_sol_mts(A,B):
    xr = np.zeros([len(A),1],dtype='float')
    idr = len(A)-1
    while idr >= 0:
        z = idr+1
        soma = 0
        while z < len(A):
            soma = soma+A[idr,z]*xr[z]
            z=z+1
            
        xr[idr] = (B[idr]-soma)/A[idr,idr]
        idr=idr-1
        
    return(xr)

In [10]:
xr = calcula_sol_mts(A,B)
print(xr)

[[-3.]
 [ 0.]
 [ 2.]
 [ 4.]]


In [13]:
def elimina_gauss(A,B):
    Ac = np.copy(A)
    Bc = np.copy(B)
    for i in range(0,len(Ac)-1):
        pivo = Ac[i,i]
        for j in range(i+1,len(Ac)):
            
            m = (-1)*Ac[j,i]/Ac[i,i]
            Ac[j,:] = Ac[i,:]*m + Ac[j,:]
            Bc[j] = Bc[i]*m + Bc[j]
            
    return(Ac,Bc)
            

In [12]:
ordem = int(input('Fornecer a ordem do sistema de equações: '))
A = np.zeros([ordem,ordem],dtype='float')
B = np.zeros([ordem,1],dtype='float')

Fornecer a ordem do sistema de equações: 3


In [14]:
for i in range(0,ordem):
    for j in range(0,ordem):
        A[i,j] = float(input('Elemento de pos. (%d,%d) da matriz A: ' %(i+1,j+1)))
        

for i in range(0,ordem):
    B[i] = float(input('Elemento de pos. %d do vetor B: ' %(i+1)))
    
print(A)
print(B)

Elemento de pos. (1,1) da matriz A: 1
Elemento de pos. (1,2) da matriz A: -3
Elemento de pos. (1,3) da matriz A: 2
Elemento de pos. (2,1) da matriz A: -2
Elemento de pos. (2,2) da matriz A: 8
Elemento de pos. (2,3) da matriz A: -1
Elemento de pos. (3,1) da matriz A: 4
Elemento de pos. (3,2) da matriz A: -6
Elemento de pos. (3,3) da matriz A: 5
Elemento de pos. 1 do vetor B: 11
Elemento de pos. 2 do vetor B: -15
Elemento de pos. 3 do vetor B: 29
[[ 1. -3.  2.]
 [-2.  8. -1.]
 [ 4. -6.  5.]]
[[ 11.]
 [-15.]
 [ 29.]]


In [15]:
[At,Bt] = elimina_gauss(A,B)
print(At)
print(Bt)

[[  1.  -3.   2.]
 [  0.   2.   3.]
 [  0.   0. -12.]]
[[ 11.]
 [  7.]
 [-36.]]


In [16]:
xr = calcula_sol_mts(At,Bt)
print(xr)

[[ 2.]
 [-1.]
 [ 3.]]


In [17]:
#Cálculo do resíduo:
r = B - A@xr
print(r)

[[0.]
 [0.]
 [0.]]


In [18]:
def calcula_determinante(A):
    Ac = np.copy(A)
   
    for i in range(0,len(Ac)-1):
        pivo = Ac[i,i]
        for j in range(i+1,len(Ac)):
            
            m = (-1)*Ac[j,i]/Ac[i,i]
            Ac[j,:] = Ac[i,:]*m + Ac[j,:]
            
            
    det = 1
    for i in range (0,len(Ac)):
        det = det*Ac[i,i]
    
    return det
    
    
    

In [19]:
ordem = int(input('Fornecer a ordem do sistema de equações: '))
A = np.zeros([ordem,ordem],dtype='float')

Fornecer a ordem do sistema de equações: 4


In [20]:
for i in range(0,ordem):
    for j in range(0,ordem):
        A[i,j] = float(input('Elemento de pos. (%d,%d) da matriz A: ' %(i+1,j+1)))

Elemento de pos. (1,1) da matriz A: 6
Elemento de pos. (1,2) da matriz A: -2
Elemento de pos. (1,3) da matriz A: 2
Elemento de pos. (1,4) da matriz A: 4
Elemento de pos. (2,1) da matriz A: 12
Elemento de pos. (2,2) da matriz A: -8
Elemento de pos. (2,3) da matriz A: 6
Elemento de pos. (2,4) da matriz A: 10
Elemento de pos. (3,1) da matriz A: 3
Elemento de pos. (3,2) da matriz A: -13
Elemento de pos. (3,3) da matriz A: 9
Elemento de pos. (3,4) da matriz A: 3
Elemento de pos. (4,1) da matriz A: -6
Elemento de pos. (4,2) da matriz A: 4
Elemento de pos. (4,3) da matriz A: 1
Elemento de pos. (4,4) da matriz A: -18


In [21]:
print(A)

[[  6.  -2.   2.   4.]
 [ 12.  -8.   6.  10.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]]


In [22]:
det = calcula_determinante(A)
print(det)

144.0


In [24]:
np.linalg.det(A)

144.0