In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np

In [2]:
ordem = int(input('Fornecer a ordem do sistema de equações: '))
A = np.zeros([ordem,ordem],dtype='float')

Fornecer a ordem do sistema de equações: 3


In [3]:
for i in range(0,ordem):
    for j in range(0,ordem):
        A[i,j] = float(input('Elemento de pos. (%d,%d) da matriz A: ' %(i+1,j+1)))
        
    
print(A)

Elemento de pos. (1,1) da matriz A: 1
Elemento de pos. (1,2) da matriz A: 2
Elemento de pos. (1,3) da matriz A: -1
Elemento de pos. (2,1) da matriz A: -1
Elemento de pos. (2,2) da matriz A: 2
Elemento de pos. (2,3) da matriz A: 0
Elemento de pos. (3,1) da matriz A: 2
Elemento de pos. (3,2) da matriz A: 1
Elemento de pos. (3,3) da matriz A: -1
[[ 1.  2. -1.]
 [-1.  2.  0.]
 [ 2.  1. -1.]]


In [4]:
def elimina_gauss_pivoteamento(A,B):
    Ac = np.copy(A)
    Bc = np.copy(B)
    for i in range(0,len(Ac)-1):
        pivo = Ac[i,i]
        z = i+1
        achou = 0
        linha = i
        while z < len(Ac):
            if abs(Ac[z,i]) > abs(pivo):
                pivo = Ac[z,i]
                linha = z
                achou = 1
            z=z+1
        if achou == 1:
            Aux = np.copy(Ac)
            Ac[i,:] = np.copy(Ac[linha,:])
            Ac[linha,:] = np.copy(Aux[i,:])
            Aux = np.copy(Bc)
            Bc[i] = Bc[linha]
            Bc[linha] = Aux[i]
        
                
            
        for j in range(i+1,len(Ac)):
            
            m = (-1)*Ac[j,i]/Ac[i,i]
            Ac[j,:] = Ac[i,:]*m + Ac[j,:]
            Bc[j] = Bc[i]*m + Bc[j]
            
    return(Ac,Bc)

In [9]:
def calcula_sol_mts(A,B):
    xr = np.zeros([len(A),1],dtype='float')
    idr = len(A)-1
    while idr >= 0:
        z = idr+1
        soma = 0
        while z < len(A):
            soma = soma+A[idr,z]*xr[z]
            z=z+1
            
        xr[idr] = (B[idr]-soma)/A[idr,idr]
        idr=idr-1
        
    return(xr)

In [6]:
I = np.eye(3)

In [7]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
B1 = I[:,0]
B1 = np.reshape(B1,(ordem,1))
B2 = I[:,1]
B2 = np.reshape(B2,(ordem,1))
B3 = I[:,2]
B3 = np.reshape(B3,(ordem,1))
print(B1,B2,B3)

[[1.]
 [0.]
 [0.]] [[0.]
 [1.]
 [0.]] [[0.]
 [0.]
 [1.]]


In [35]:
[Ac1,Bc1] = elimina_gauss_pivoteamento(A,B1)
x1 = calcula_sol_mts(Ac1,Bc1)

[Ac2,Bc2] = elimina_gauss_pivoteamento(A,B2)
x2 = calcula_sol_mts(Ac2,Bc2)

[Ac3,Bc3] = elimina_gauss_pivoteamento(A,B3)
x3 = calcula_sol_mts(Ac3,Bc3)

Sol = np.zeros([ordem,ordem],dtype='float')
Sol = np.column_stack((x1,x2,x3))
print(Sol)


[[-2.  1.  2.]
 [-1.  1.  1.]
 [-5.  3.  4.]]


In [36]:
Res = A@Sol
print(Res)

[[1.0000000e+00 4.4408921e-16 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]


In [37]:
def elimina_gauss(A,B):
    Ac = np.copy(A)
    Bc = np.copy(B)
    for i in range(0,len(Ac)-1):
        pivo = Ac[i,i]
        for j in range(i+1,len(Ac)):
            
            m = (-1)*Ac[j,i]/Ac[i,i]
            Ac[j,:] = Ac[i,:]*m + Ac[j,:]
            Bc[j] = Bc[i]*m + Bc[j]
            
    return(Ac,Bc)

In [56]:
ordem = int(input('Fornecer a ordem do sistema de equações: '))
A = np.zeros([ordem,ordem],dtype='float')
for i in range(0,ordem):
    for j in range(0,ordem):
        A[i,j] = float(input('Elemento de pos. (%d,%d) da matriz A: ' %(i+1,j+1)))
        
    
print(A)

Fornecer a ordem do sistema de equações: 3
Elemento de pos. (1,1) da matriz A: 1
Elemento de pos. (1,2) da matriz A: 1
Elemento de pos. (1,3) da matriz A: 1
Elemento de pos. (2,1) da matriz A: 1
Elemento de pos. (2,2) da matriz A: 0
Elemento de pos. (2,3) da matriz A: 10
Elemento de pos. (3,1) da matriz A: 0
Elemento de pos. (3,2) da matriz A: 10
Elemento de pos. (3,3) da matriz A: 1
[[ 1.  1.  1.]
 [ 1.  0. 10.]
 [ 0. 10.  1.]]


In [57]:
B = np.zeros([ordem,1],dtype='float')
for i in range(0,ordem):
    B[i] = float(input('Elemento de pos. %d do vetor B: ' %(i+1)))
    
print(B)

Elemento de pos. 1 do vetor B: 0
Elemento de pos. 2 do vetor B: -48
Elemento de pos. 3 do vetor B: 25
[[  0.]
 [-48.]
 [ 25.]]


In [60]:
[Ac1,Bc1] = elimina_gauss_pivoteamento(A,B)
print(Ac1,Bc1)
x1 = calcula_sol_mts(Ac1,Bc1)
print(x1)

[[ 1.   1.   1. ]
 [ 0.  10.   1. ]
 [ 0.   0.   9.1]] [[  0. ]
 [ 25. ]
 [-45.5]]
[[ 2.]
 [ 3.]
 [-5.]]


In [61]:
[Ac2,Bc2] = elimina_gauss(A,B)
print(Ac2,Bc2)
x2 = calcula_sol_mts(Ac2,Bc2)
print(x2)

[[ 1.  1.  1.]
 [ 0. -1.  9.]
 [ 0.  0. 91.]] [[   0.]
 [ -48.]
 [-455.]]
[[ 2.]
 [ 3.]
 [-5.]]


In [62]:
def checa_pivo_nulo(A,B):
    Ac = np.copy(A)
    Bc = np.copy(B)
    for i in range(0,len(Ac)-1):
        pivo = Ac[i,i]
        if pivo == 0:
            z = i+1
            achou = 0
            linha = i
            while z < len(Ac):
                if abs(Ac[z,i]) > abs(pivo):
                    pivo = Ac[z,i]
                    linha = z
                    achou = 1
                z=z+1
            if achou == 1:
                Aux = np.copy(Ac)
                Ac[i,:] = np.copy(Ac[linha,:])
                Ac[linha,:] = np.copy(Aux[i,:])
                Aux = np.copy(Bc)
                Bc[i] = Bc[linha]
                Bc[linha] = Aux[i]
        
                
            
       
            
    return(Ac,Bc)

In [67]:
def Gauss_Jordan(A,B):
    Ac = np.copy(A)
    Bc = np.copy(B)
    for i in range(0,len(Ac)):
        pivo = Ac[i,i]
        Ac[i,:] = Ac[i,:]/pivo
        Bc[i] = Bc[i]/pivo
        for j in range(0,len(Ac)):
            
            if j != i:
                m = (-1)*Ac[j,i]
                Ac[j,:] = Ac[i,:]*m + Ac[j,:]
                Bc[j] = Bc[i]*m + Bc[j]
            
    return(Ac,Bc)

In [64]:
ordem = int(input('Fornecer a ordem do sistema de equações: '))
A = np.zeros([ordem,ordem],dtype='float')
for i in range(0,ordem):
    for j in range(0,ordem):
        A[i,j] = float(input('Elemento de pos. (%d,%d) da matriz A: ' %(i+1,j+1)))
        
    
print(A)

B = np.zeros([ordem,1],dtype='float')
for i in range(0,ordem):
    B[i] = float(input('Elemento de pos. %d do vetor B: ' %(i+1)))
    
print(B)

Fornecer a ordem do sistema de equações: 3
Elemento de pos. (1,1) da matriz A: 2
Elemento de pos. (1,2) da matriz A: 1
Elemento de pos. (1,3) da matriz A: -1
Elemento de pos. (2,1) da matriz A: 5
Elemento de pos. (2,2) da matriz A: 2
Elemento de pos. (2,3) da matriz A: 2
Elemento de pos. (3,1) da matriz A: 3
Elemento de pos. (3,2) da matriz A: 1
Elemento de pos. (3,3) da matriz A: 1
[[ 2.  1. -1.]
 [ 5.  2.  2.]
 [ 3.  1.  1.]]
Elemento de pos. 1 do vetor B: 1
Elemento de pos. 2 do vetor B: -4
Elemento de pos. 3 do vetor B: 5
[[ 1.]
 [-4.]
 [ 5.]]


In [71]:
[Ac,Bc] = checa_pivo_nulo(A,B)
print(Ac)
print(Bc)

[[ 2.  1. -1.]
 [ 5.  2.  2.]
 [ 3.  1.  1.]]
[[ 1.]
 [-4.]
 [ 5.]]


In [68]:
[Aj,Bj] = Gauss_Jordan(Ac,Bc)
print(Aj)
print(Bj)

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[[ 14.]
 [-32.]
 [ -5.]]


In [69]:
res = A@Bj-B
print(res)

[[0.]
 [0.]
 [0.]]


In [74]:
def Gauss_Jordan_Inversa(A):
    Ac = np.copy(A)
    Bc = np.eye(len(Ac))
    for i in range(0,len(Ac)):
        pivo = Ac[i,i]
        Ac[i,:] = Ac[i,:]/pivo
        Bc[i,:] = Bc[i,:]/pivo
        for j in range(0,len(Ac)):
            
            if j != i:
                m = (-1)*Ac[j,i]
                Ac[j,:] = Ac[i,:]*m + Ac[j,:]
                Bc[j,:] = Bc[i,:]*m + Bc[j,:]
               
            
    return Bc

In [75]:
Ainv = Gauss_Jordan_Inversa(Ac)
print(Ac)
print(Ainv)
print(Ac@Ainv)

[[ 2.  1. -1.]
 [ 5.  2.  2.]
 [ 3.  1.  1.]]
[[ 0.  -1.   2. ]
 [ 0.5  2.5 -4.5]
 [-0.5  0.5 -0.5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
